### PR TITLE
Update azure.md

### PR DESCRIPTION
**Pull request by xt0rted**
Fixed the quotes in the deploy script step, and the name of the azure blob storage brain as per [hubot-azure-scripts](https://github.com/bfcamara/hubot-azure-scripts/blob/2105b4cb3dc331157e19c90e6dabf2247e6553a6/brain/storage-blob-brain.coffee)

### CODE REVIEW

**Comment by xt0rted** [comment]
While setting this up on azure I also found that there was an additional step of updating the node version in `iisnode.yml` to match that of the `WEBSITE_NODE_DEFAULT_VERSION` environment variable. The value in `iisnode.yml` was `0.10.0` while azure was set to use `4.2.4`. Hubot wouldn't run until these versions matched.

**Comment by gep13** [comment]
@xt0rted did you have any issues around the following:

```
Application has thrown an uncaught exception and is terminated:
Error: Cannot find module 'coffee-script/register'
```

Did I miss something when setting this up?

**Comment by technicalpickles** [comment]
It seems the hubot-azure-scripts package changed the path. I can merge this, but if you see any other problems deploying on Azure @gep13  or @xt0rted, can you please open new issues/PRs?

**Comment by gep13** [comment]
@technicalpickles we were actually able to get this working.  And the steps documented here: https://github.com/Odonno/gitter-bot-how-to#host-on-azure

Thanks!

**Pull request merged**
