### PR TITLE
[index.md] fix scripting link

### PR DESCRIPTION
**Pull request by ChrisLundquist**

### CODE REVIEW

**Comment by technicalpickles** [comment]
This is intentional for now so it can be viewed on hubot.github.com, see https://github.com/github/hubot/issues/916 for more context

**Comment by ChrisLundquist** [comment]
Right, the link on hubot.github.com is broken.

it points to.
https://hubot.github.com/docs/scripting.md

**Comment by technicalpickles** [comment]
Right, reading is hard. Sorry about that.

**Comment by ChrisLundquist** [comment]
:sparkling_heart:

**Pull request merged**
