### PR TITLE
Update documentation to use `res` instead of `msg`

### PR DESCRIPTION
**Pull request by geoffreyanderson**

### CODE REVIEW

**Comment by geoffreyanderson** [comment]
This and https://github.com/github/generator-hubot/pull/36 are targeted at answering #786.

**Comment by technicalpickles** [comment]
Thanks for taking a stab at this! I'm surprised there was only one reference to `Response` as `res` in the code base.

This should be good to merge, I'm just little it sit out a little in case we can think of a reason this is a bad idea in https://github.com/github/hubot/issues/786 :grin:

**Comment by geoffreyanderson** [comment]
Sounds good to me :+1:

**Comment by technicalpickles** [comment]
Finally ready for this :grin: Doing a review, found just one `msg` references:

* https://github.com/github/hubot/blob/master/src/robot.coffee#L64-L65 (invokeErrorHandlers's definition is correctly using res though)

**Comment by geoffreyanderson** [comment]
yay! :beers:

**Comment by MrSaints** [comment]
A lot of scripts (past and present) uses `res` when making HTTP requests, e.g. https://github.com/hubot-scripts/hubot-google-translate/blob/master/src/google-translate.coffee#L103

```coffee
get() (err, res, body) ->
```

Anyone working with HTTP requests should keep this in mind otherwise you may end up with `undefined` errors. I thought I should raise this in case anyone is stuck in a pickle.

**Comment by technicalpickles** [comment]
I've run into it with our own hubot actually, so yeah, kind of a problem :sweat:

I think it will only affect new scripts being written though, as it's just a variable name change local to the script. I've taken to using httpRes for those, but not sure if that is best or not yet.

**Pull request merged**
