### PR TITLE
Only loadScripts once

### PR DESCRIPTION
**Pull request by technicalpickles**
This should fix https://github.com/slackhq/hubot-slack/issues/210 over in hubot-slack. I'm not sure if there's any other implications of this, like if other adapters have workarounds for this or not.

### CODE REVIEW

**Comment by michaelansel** [comment]
First pass says this should be fine. I don't think we ever intentionally reload scripts.

**Comment by zapbuild** [comment]
When you are going to merge it into master branch. I'm getting the same issue "Hubot repeating himself twice after reconnect". I'm using hubot-slack adapter.

**Comment by technicalpickles** [comment]
Soon. I'm testing this branch in production, and hoping to verify the double-response is fixed.

**Comment by technicalpickles** [comment]
I still have this out in production. There weren't any reconnect events to verify this fixes it yet though :sweat:

**Comment by ThomasRooney** [comment]
I can verify that this has fixed my issue with multiple responses after a reconnect. Can we get it merged?

**Comment by Floby** [comment]
\o/

**Comment by Floby** [comment]
I take it this has been published with `2.17.0` ?

**Comment by bhuga** [comment]
Yes, this is in `2.17.0`.

**Comment by Floby** [comment]
ok, thanks a lot =)

**Pull request merged**
