### PR TITLE
Prepare for v2.15.0 release

### PR DESCRIPTION
**Pull request by michaelansel**
* Document another middleware pattern https://github.com/github/hubot/pull/1017 @kristenmills 
* Make Robot.respondPattern a public method https://github.com/github/hubot/pull/1011 @sdimkov 
* Make "done" argument optional for middleware https://github.com/github/hubot/pull/1028 @michaelansel

All changes: https://github.com/github/hubot/compare/v2.14.0...master

@github/open-source-hubot-maintainers

### CODE REVIEW

**Comment by michaelansel** [comment]
Cutting a new release quicker than normal to see if it fixes the broken state on npmjs.com

**Comment by michaelansel** [comment]
```bash
git pull upstream master
npm publish
git tag v2.15.0
git push upstream master --tags
```

Maybe, one day, automation will happen...

**Comment by technicalpickles** [comment]
@michaelansel `script/release` does most of that. I think the main difference is your `origin` refers to your fork.

**Comment by michaelansel** [comment]
Yeah, I was also referring to automating the changelog/PR generation

**Comment by michaelansel** [comment]
Published: https://github.com/github/hubot/compare/v2.14.0...v2.15.0

**Comment by michaelansel** [comment]
And it appears to have fixed whatever state was corrupted in npm.

**Pull request merged**
