### PR TITLE
Prepare for 2.11.1 release

### PR DESCRIPTION
**Pull request by technicalpickles**
Includes:

* https://github.com/github/hubot/pull/848
* https://github.com/github/hubot/pull/841

cc @aroben @aaronstaves @afeld @michaelansel

### CODE REVIEW

**Comment by afeld** [comment]
Weird that there are two Travis statuses above... but :+1:

**Comment by technicalpickles** [comment]
Looks like Travis is unhappy with node 0.8 https://travis-ci.org/github/hubot/jobs/51022909

```
npm ERR! Error: No compatible version found: mocha@'^2.1.0'
npm ERR! Valid install targets:
npm ERR! ["0.0.1-alpha1","0.0.1-alpha2","0.0.1-alpha3","0.0.1-alpha4","0.0.1-alpha5","0.0.1-alpha6","0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.0.6","0.0.7","0.0.8","0.1.0","0.2.0","0.3.0","0.3.1","0.3.2","0.3.3","0.3.4","0.3.6","0.4.0","0.5.0","0.6.0","0.7.0","0.7.1","0.8.0","0.8.1","0.9.0","0.10.0","0.10.1","0.10.2","0.11.0","0.12.0","0.12.1","0.13.0","0.14.0","0.14.1","1.0.0","1.0.1","1.0.2","1.0.3","1.1.0","1.2.0","1.2.1","1.2.2","1.3.0","1.3.1","1.3.2","1.4.0","1.4.1","1.4.2","1.4.3","1.5.0","1.6.0","1.7.0","1.7.1","1.7.2","1.7.3","1.7.4","1.8.0","1.8.1","1.8.2","1.9.0","1.10.0","1.11.0","1.12.0","1.12.1","1.13.0","1.14.0","1.15.0","1.15.1","1.16.0","1.16.1","1.16.2","1.17.0","1.17.1","1.18.0","1.18.1","1.18.2","1.19.0","1.20.0","1.20.1","1.21.0","1.21.1","1.21.2","1.21.3","1.21.4","1.21.5","2.0.0","2.0.1","2.1.0"]
npm ERR!     at installTargetsError (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /home/travis/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:641:10
npm ERR!     at saved (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:302:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! Error: No compatible version found: hubot-mock-adapter@'^1.0.0'
npm ERR! Valid install targets:
npm ERR! ["1.0.0"]
npm ERR!     at installTargetsError (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /home/travis/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:641:10
npm ERR!     at RegClient.get_ (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:101:14)
npm ERR!     at RegClient.<anonymous> (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:37:12)
npm ERR!     at fs.readFile (fs.js:181:14)
npm ERR!     at Object.oncomplete (fs.js:302:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
```

**Comment by afeld** [comment]
That's strange... both packages should be 0.8-compatible, as far as their `package.json` is concerned.

* https://github.com/mochajs/mocha/blob/2.1.0/package.json#L39
* https://github.com/blalor/hubot-mock-adapter/blob/v1.0.0/package.json

I can try installing 0.8 locally later if we think this is a legitimate failure.

**Comment by technicalpickles** [comment]
It seems more like an issue with npm not liking the dependency using `^` on node 0.8.

**Comment by technicalpickles** [comment]
@afeld fixed this the failure in https://github.com/github/hubot/issues/869 , thanks!

**Pull request merged**
