### PR TITLE
add automated tests

### PR DESCRIPTION
**Pull request by afeld**
I just made a couple tweaks on top of what @technicalpickles did in the [`testing`](https://github.com/github/hubot/tree/testing) branch... not full coverage by any means, but it's a start.

### CODE REVIEW

**Comment by michaelansel** [comment]
@technicalpickles Is this the style of testing you would like to see moving forward? If so, I'll put together a PR with tests for the areas affected by #803.

**Comment by michaelansel** [comment]
First round of tests written for the message processing flow; I'll rebase and open a PR as soon as this merges (unless there is a way to integrate my change into this PR?).

michaelansel/hubot@ad5580fe932d2aec6bb377fae9354181ab5bf087

**Comment by michaelansel** [comment]
cc #676 #848 which fix the EventEmitter noise

**Comment by technicalpickles** [comment]
Running this locally, I have a failing test. Maybe a weird environment thing?

```
  1) Robot Unit Tests #receive calls all registered listeners:
     TypeError: Object #<Assertion> has no method 'callCount'
      at Context.<anonymous> (/Users/technicalpickles/github/hubot/test/robot_test.coffee:57:48)
      at Test.Runnable.run (/Users/technicalpickles/github/hubot/node_modules/mocha/lib/runnable.js:211:32)
      at Runner.runTest (/Users/technicalpickles/github/hubot/node_modules/mocha/lib/runner.js:372:10)
      at /Users/technicalpickles/github/hubot/node_modules/mocha/lib/runner.js:448:12
      at next (/Users/technicalpickles/github/hubot/node_modules/mocha/lib/runner.js:297:14)
      at /Users/technicalpickles/github/hubot/node_modules/mocha/lib/runner.js:307:7
      at next (/Users/technicalpickles/github/hubot/node_modules/mocha/lib/runner.js:245:23)
      at Object._onImmediate (/Users/technicalpickles/github/hubot/node_modules/mocha/lib/runner.js:274:5)
      at processImmediate [as _immediateCallback] (timers.js:330:15)

```

**Comment by technicalpickles** [comment]
I pushed this up to github/hubot's testing branch.

I *bet* it has to do with one of the test dependency versions. Probably worth locking those down to known versions that work, rather than using `*`.

**Comment by technicalpickles** [comment]
After nuking my `node_modules`, I ended up with the problem described in https://github.com/github/generator-hubot/pull/24

> I bet it has to do with one of the test dependency versions. Probably worth locking those down to known versions that work, rather than using *.

Was definitely this. 9d9939e5dfba9f845ba0cc2e1b24dd4e3aa7119b should fix it.

**Comment by technicalpickles** [comment]
I think CI was failing for the same reason. Filed https://github.com/afeld/hubot/issues/2 to fix that.

**Comment by technicalpickles** [comment]
Feeling good about this. I'm going to merge the testing branch now.

**Comment by afeld** [comment]
Look at all that collaboration on this addition!

high five

**Pull request closed without merging**
