### PR TITLE
Add link to the Telegram Bot API adapter.

### PR DESCRIPTION
**Pull request by arcturial**
I included a link to a library I developed that allows interacting with [Telegram](https://telegram.org/) using the [Telegram Bot API](https://core.telegram.org/bots/api).

The library used to connect to Telegram currently supports all the available calls.

### CODE REVIEW

**Comment by lukefx** [comment]
Hey, same project here: https://github.com/lukefx/hubot-telegram
Why not collaborate on only one codebase?

**Comment by arcturial** [comment]
I would be happy to collaborate, it was published around roughly the same time it seems. I would like to make use of the telegrambot adapter though to abstract the actual API interactions from the adapter code itself.

**Comment by michaelansel** [comment]
When there is agreement on the canonical telegram adapter, I'll merge a PR pointing there. If there is disagreement, please update the PR to point to both adapters.

**Comment by arcturial** [comment]
Thanks, I will have a discussion with @lukefx in a separate thread. Will update this PR as soon as it is resolved.

**Comment by arcturial** [comment]
I have updated the link to point to https://github.com/lukefx/hubot-telegram where both authors code have been merged. You can now accept the PR if you are happy.

**Comment by michaelansel** [comment]
Thanks for sorting that out!

**Pull request merged**
