### PR TITLE
migrate user.coffee to es6 #1138

### PR DESCRIPTION
**Pull request by gasolin**
- migrate user.coffee to es6
- introduce babel to compile it.
- add npm build scripts to put compiled file into dist/ folder
- fix the require path of modules

### CODE REVIEW

**Comment by technicalpickles** [comment]
@gasolin looks like this is failing on nodejs 0.10 due to Symbol being undefined. We're not quite ready to drop support for 0.10 at this point yet.

**Comment by gasolin** [comment]
Thanks for review.

If `node 0.10` support is required, add [core-js](https://github.com/zloirock/core-js) polyfill could fix that. I've rebased the patch, and the test on node 0.10 has passed. Please take a look again.

**Comment by gasolin** [comment]
BTW, I've converted `user_test.coffee` and test fine on 0.10 as well. But it might be safer to do in separate patch to make sure everything works fine.

**Comment by bkeepers** [comment]
@gasolin, thanks for the pull request! We're working on returning Hubot to its former glory, and as part of that we're establishing a new process for adding new features called [Hubot Evolution](https://github.com/hubotio/evolution). The migration from CoffeeScript to ES6 is _very_ high on our list of priorities. We will be opening a proposal in the evolution repo soon and being talking about a plan for converting all of Hubot to ES6.

I'm going to close this PR in the mean time, but thank you for kicking this process off! Let me know if you have any questions or concerns.

**Comment by gasolin** [comment]
no problem, I'd happy to help if you want to discuss about the evolving plan

**Comment by bkeepers** [comment]
@gasolin great! We should be opening a proposal early next week and will cc you on it.

cc @gr2m

**Pull request closed without merging**
