### PR TITLE
Prepare for v2.14.0 release

### PR DESCRIPTION
**Pull request by michaelansel**
* Lots of documentation tweaks and new adapters #968 #971 #991 #993 #999 #1004 #1006 #1007 @MyvarHD @technicalpickles @jennifersmith @sdimkov @arcturial @jexe @geoffreyanderson
* Add a code of conduct #1005 @bkeepers 
* Add Listener Middleware #803 @michaelansel

All changes: https://github.com/github/hubot/compare/v2.13.2...release-v2.14.0

@github/open-source-hubot-maintainers

### CODE REVIEW

**Comment by michaelansel** [comment]
Preparing a prerelease and holding for a week. Doc changes will be synced to hubot.github.com when the release is published.

**Comment by michaelansel** [comment]
Okay, for the prerelease, I'm going to:
* merge this PR (locking in the release, but not publishing it)
* manually walk through `script/release`
```bash
git pull upstream master
npm publish --tag next
git tag v2.14.0
git push origin master --tags
```
* at this point, early adopters can `npm install hubot@latest`
* when the time is right, promote "next" to "latest"
```bash
npm dist-tag add hubot@v2.14.0 latest
```
* update hubot.github.com with the matching documentation

@github/open-source-hubot-maintainers, can I get a :+1: on that plan?

**Comment by bhuga** [comment]
Love it.

**Comment by michaelansel** [comment]
Okay, release cut and published. https://github.com/github/hubot/compare/v2.13.2...v2.14.0

Confirmed that `npm install hubot@next` works and updated our bot to point to `next` (in package.json)
```json
{
  "dependencies": {
    "hubot": "next"
  }
}
```

I'll let this sit till sometime next week and then update `latest` to v2.14.0

**Comment by bkeepers** [comment]
Nice work!

**Comment by cycomachead** [comment]
Been using this for a couple days, and so far no issues! :+1: 

(Haven't had time to write new middleware, yet,...I'll get there!).

**Comment by michaelansel** [comment]
Never got this deployed at work, but we've been running all but the last commit for months. Any objections to promoting this to `latest`?

@github/open-source-hubot-maintainers

```bash
npm dist-tag add hubot@v2.14.0 latest
```

**Comment by bhuga** [comment]
We aren't stress testing the middleware (I need #1019), but I just deployed the `next` branch for our install. How about marking it as `latest` after one more day with no issues?

**Comment by michaelansel** [comment]
:+1: I'll promote it tomorrow

**Comment by bhuga** [comment]
We ran this for a day with no catastrophes :+1:

**Comment by michaelansel** [comment]
Release promoted! Looks like something weird is happening with the NPM site though... Package installs find though.

https://www.npmjs.com/package/hubot

I'll plan to cut another release soon and see if that fixes it.

**Comment by michaelansel** [comment]
Doc site updated to match

**Pull request merged**
