### PR TITLE
update travis.yml

### PR DESCRIPTION
**Pull request by scboucher**
Added node v4 and node v0.12, removed  node v0.11

### CODE REVIEW

**Comment by michaelansel** [comment]
@technicalpickles: Any objection to removing node 0.11 in favor of 0.12 and 4.0? I'm all :+1: on this (and also super pleased we are 100% passing on 4.0 with zero effort)

**Comment by technicalpickles** [comment]
[Odd versions](https://github.com/nodejs/node-v0.x-archive/wiki/FAQ) are considered 'unstable'  so :+1:  to removing 0.11 in favor of 0.12 and adding newer 4.0.

**Comment by technicalpickles** [comment]
Not sure what changed, but the 0.8 build is sad:

```
npm ERR! Error: No compatible version found: chalk@'^1.0.0'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","0.2.0","0.2.1","0.3.0","0.4.0","0.5.0","0.5.1","1.0.0","1.1.0","1.1.1"]
npm ERR!     at installTargetsError (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /home/travis/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:641:10
npm ERR!     at saved (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:302:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
```

**Comment by scboucher** [comment]
I added stuff to gitignore for Intellij users.

**Comment by michaelansel** [comment]
There are a lot of additional changes here. Please clean this up to just the change you want merged.

**Comment by scboucher** [comment]
see #1068

**Pull request closed without merging**
