### PR TITLE
Prepare for v2.13.2 release

### PR DESCRIPTION
**Pull request by michaelansel**
* Minor documentation updates #955 #974 #973 @praseodym @bhuga @Sing-Li 
* Add Robot.respondPattern private to improve testability https://github.com/github/hubot/pull/975 @michaelansel
* Ignore .node-version so it isn't included in releases https://github.com/github/hubot/pull/980 @jasonkarns 

cc @github/open-source-hubot-maintainers

Changes: https://github.com/github/hubot/compare/v2.13.1...release-v2.13.2

### CODE REVIEW

**Comment by technicalpickles** [comment]
Looks good :+1:

**Comment by michaelansel** [comment]
Published! https://github.com/github/hubot/compare/v2.13.1...v2.13.2

**Comment by technicalpickles** [comment]
Behold, @michaelansels' first release!

jake-the-dog-super-happy

**Comment by michaelansel** [comment]
I am so looking forward to automating this :star2:

**Comment by bkeepers** [comment]
:zap:

**Pull request merged**
