### PR TITLE
Add support for global http options

### LINKED ISSUE #287: Hubot behind a proxy
I'm behind a proxy, and while `hubot ping` works just fine, `math me 2+2` doesn't work. In fact, any step that uses a `get()` in the script just doesn't work at all. How do I either:
1. Tell Hubot to use a proxy when doing a `.get()`?
2. Get some additional debugging out of Hubot so that I can diagnose why things aren't working?

Thanks!

### PR DESCRIPTION
**Pull request by michaelansel**
Primary purpose is to support global proxy settings in corporate environments

Closes #287 and #731

### CODE REVIEW

**Comment by michaelansel** [comment]
Soft dependency on technoweenie/node-scoped-http-client#31 (code will work, but docs are a lie until that merges)

**Comment by michaelansel** [comment]
Dependent commit merged, so this should be good to go now

**Comment by michaelansel** [comment]
Dependent commit merged; just waiting on a release including the new behavior

**Comment by technicalpickles** [comment]
0.11.0 is released now

**Pull request merged**
