### PR TITLE
docs: add link to symphony adapater

### PR DESCRIPTION
**Pull request by jonfreedman**
Updating the adapter list as per https://github.com/github/hubot/issues/1216

### CODE REVIEW

**Comment by maoo** [comment]
Any update on this? The hubot-symphony integration is already 8 months old and works quite well, which is why we'd love to see it listed as Hubot adapter.

Thanks in advance!

**Comment by francesdadzie123** [comment]
there was a problem communicating with google services i think i need to to up my phone again then  google will work because my phone is not for free settings

**Comment by maoo** [comment]
Hi @technicalpickles , sorry to ping you directly, but I'm not sure how to move this issue forward and - since you're the last committer of `adapters.md` - I thought you could help us understanding how to move forward. Thanks in advance!

**Comment by bkeepers** [comment]
The [list of hubot adapters in the hubot documentation](https://hubot.github.com/docs/adapters/) is being replaced with a link to a [GitHub topic search](https://github.com/search?q=topic%3Ahubot-adapter&type=Repositories). Add the `hubot-adapter` [topic](https://help.github.com/articles/classifying-your-repository-with-topics/) to your repository on GitHub to include it in this list.

/cc https://github.com/github/hubot/pull/1320

**Comment by jonfreedman** [comment]
@bkeepers - I've tagged our repository, look forward to the docs being updated.

**Pull request closed without merging**
